FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY zitadel-custom /app/zitadel

RUN chmod +x /app/zitadel

ENTRYPOINT ["/app/zitadel"]
